from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', index),
    path('users/', views.users),
    path('accounts/login/', login),
    path('login/', login),
    path('profile/', profile),
    path('setting/', setting),
    path('register/', register),
    path('getdata/', getdata),
    path('gettask/', gettask),
    path('delete_user/', delete_user),
    path('delete_task/', delete_task),
    path('edit_user/<int:user_id>/', edit_user),
    path('edit_task/<int:user_id>/', edit_task),
    path('update_user/', update_user),
    path('update_task/', update_task),
    path('login_check/', login_check),
    path('logout/', logout),
    path('edit/', edit_user),
    path('edit_task/', edit_task),
    path('users/', users),
    path('dashboard/', dashboard),
    path('tasks/', tasks),
    path("toggle_status/", views.toggle_status),
    path('add_user/', add_user),
    path('add_task/', add_task),
    path('api/login/', views.login),
    path('api/users/', views.get_users),
    path('api/tasks/', views.taskdetails),
    path('api/task/<int:user_id>/', views.taskdetail),
    path('api/deletetask/<int:task_id>/', views.deletetask),
    path('api/gettask/', views.gettask),
    path('tasks/', views.tasks),
    path('api/updatetask/', views.updatetask),
    path('api/getdata/', views.getdata),
]