# Generated by Django 6.0.1 on 2026-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
