# Generated by Django 6.0.1 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_detail_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
