# Generated by Django 6.0.1 on 2026-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_detail_address_alter_user_detail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
