# Generated by Django 6.0.1 on 2026-03-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_detail_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='address',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='user_detail',
            old_name='name',
            new_name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='age',
        ),
    ]
