# Generated by Django 6.0.1 on 2026-03-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_address_user_detail_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='First_Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='user_detail',
            old_name='Last_Name',
            new_name='LastName',
        ),
    ]
