# Generated by Django 6.0.1 on 2026-03-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_first_name_user_detail_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='user_detail',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
