# Generated by Django 6.0.1 on 2026-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_firstname_user_detail_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='First_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user_detail',
            old_name='Last_Name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
