# Generated by Django 6.0.1 on 2026-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_first_name_user_detail_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
