# Generated by Django 6.0.1 on 2026-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_user_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='duedate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='progress',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_detail',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
