# Generated by Django 6.0.1 on 2026-03-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_user_detail_duedate_user_detail_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('progress', models.IntegerField(blank=True, max_length=100, null=True)),
                ('duedate', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='task',
        ),
    ]
