# Generated by Django 6.0.1 on 2026-03-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_task_detail_remove_user_detail_duedate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_detail',
            old_name='task',
            new_name='taskdetails',
        ),
        migrations.RenameField(
            model_name='task_detail',
            old_name='progress',
            new_name='totaldays',
        ),
        migrations.AddField(
            model_name='task_detail',
            name='assigndate',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='taskname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='duedate',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
