# Generated by Django 6.0.1 on 2026-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_task_task_detail_taskdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_detail',
            name='status',
        ),
        migrations.AddField(
            model_name='task_detail',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (4, 'Cancelled')], default=1),
        ),
    ]
