# Generated by Django 6.0.1 on 2026-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_task_detail_status_task_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('not done', 'Not Done')]),
        ),
    ]
