# Generated by Django 6.0.1 on 2026-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_task_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='Status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('not done', 'Not Done')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='totaldays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
