# Generated by Django 6.0.1 on 2026-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_task_detail_status_alter_task_detail_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Not Done', 'Not Done')], max_length=100),
        ),
    ]
