# Generated by Django 6.0.1 on 2026-03-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_task_detail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_detail',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='user_detail',
            old_name='status',
            new_name='Status',
        ),
    ]
