# Generated by Django 6.0.1 on 2026-03-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_task_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='assigndate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
