# Generated by Django 6.0.1 on 2026-03-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_task_detail_assigndate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='Status',
            new_name='status',
        ),
    ]
