# Generated by Django 6.0.1 on 2026-03-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_rename_status_user_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Not Done', 'Not Done')], max_length=100, null=True),
        ),
    ]
