# Generated by Django 6.0.1 on 2026-03-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_task_detail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_detail',
            name='Name',
        ),
        migrations.AddField(
            model_name='task_detail',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user_detail'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
