# Generated by Django 6.0.1 on 2026-03-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_task_detail_name_task_detail_fk_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=255)),
                ('taskdetails', models.TextField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('remaining_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user_detail')),
            ],
        ),
    ]
