# Generated by Django 6.0.1 on 2026-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_task_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_detail',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task_detail',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='task_completion',
        ),
    ]
