# Generated by Django 6.0.1 on 2026-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_task_detail_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Not Done', 'Not Done')], default='Pending', max_length=100),
        ),
    ]
