# Generated by Django 6.0.4 on 2026-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_task_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
